site_name: Challenge 1 - Andrômeda

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: red
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.tabs.sticky

repo_url: https://github.com/unb-Sistemas-de-Machine-learning/challenge_1_andromeda

extra_css:
  - assets/stylesheets/global.css
  
markdown_extensions:
  - admonition
  - tables

nav:
  - Home: index.md
  - Canvas: 
    - Guiding Questions: 01_Canvas/01_guidingQuestions.md
    - Objetivos: 01_Canvas/02_objetivos.md
