site_name: Challenge 1 - Andrômeda

theme:
  name: material
  language: pt-BR
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Modo claro

repo_url: https://github.com/unb-Sistemas-de-Machine-learning/challenge_1_andromeda

markdown_extensions:
  - admonition
  - tables

nav:
  - Home: index.md
  - Guiding Questions: guiding-questions.md
  - Canvas: canva.md
